
### 学生申诉正确的用法
POST http://localhost:8880/appeal/student_appeal
Content-Type: application/json

{
    "studentId":3120100001,
    "courseUid":"21120062",
    "classIndex":1
}



### 错误的用法 没有分数记录
POST http://localhost:8880/appeal/student_appeal
Content-Type: application/json

{
    "studentId":3120420000,
    "courseUid":"21120062",
    "classIndex":1
}