GET http://localhost:8880/student/information?userId=3170100002

###

GET http://localhost:8880/student/list

###

GET http://localhost:8880/student/list?page=1&size=101

###

POST http://localhost:8880/student/save
Content-Type: application/json

{}

###

DELETE http://localhost:8880/student/delete?userId=11111111111

###
